name: Pylint
on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        $files = Get-ChildItem -Recurse -Filter *.py | Select-Object -ExpandProperty FullName
        $output = pylint $files --output-format=text
        $output | Out-File -FilePath pylint_output.txt
        $score = $output | Select-String -Pattern "Your code has been rated at (\d+\.\d+)" | ForEach-Object { $_.Matches.Groups[1].Value }
        echo "PyLint Score: $score"
        echo "PYLINT_SCORE=$score" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Check PyLint score
      run: |
        $pylint_score = [double]$env:PYLINT_SCORE
        if ($pylint_score -lt 9.5) {
          echo "PyLint score is below 9.5. Failing the build."
          exit 1
        }
